/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

/**
 *
 * @author Aaron
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        CustomerMenuButton = new javax.swing.JButton();
        ProductMenuButton = new javax.swing.JButton();
        OrderMenuButton = new javax.swing.JButton();
        MainMenuLabel = new javax.swing.JLabel();
        CustomerPanel = new javax.swing.JPanel();
        CustomerMenuLabel = new javax.swing.JLabel();
        ProductPanel = new javax.swing.JPanel();
        ProductMenuLabel = new javax.swing.JLabel();
        OrderPanel = new javax.swing.JPanel();
        OrderMenuLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ExitDrop = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MainNavDrop = new javax.swing.JMenuItem();
        CustNavDrop = new javax.swing.JMenuItem();
        ProdNavDrop = new javax.swing.JMenuItem();
        OrdNavDrop = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 50, 850, 600));
        setMinimumSize(new java.awt.Dimension(850, 600));
        setPreferredSize(new java.awt.Dimension(850, 600));
        getContentPane().setLayout(null);

        CustomerMenuButton.setText("Customers");
        CustomerMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerMenuButtonActionPerformed(evt);
            }
        });

        ProductMenuButton.setText("Products");
        ProductMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductMenuButtonActionPerformed(evt);
            }
        });

        OrderMenuButton.setText("Orders");
        OrderMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderMenuButtonActionPerformed(evt);
            }
        });

        MainMenuLabel.setText("Main Menu");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CustomerMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(ProductMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OrderMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(MainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(MainMenuLabel)
                .addGap(36, 36, 36)
                .addComponent(CustomerMenuButton)
                .addGap(11, 11, 11)
                .addComponent(ProductMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OrderMenuButton)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        getContentPane().add(MainPanel);
        MainPanel.setBounds(0, 0, 400, 280);

        CustomerMenuLabel.setText("Customer Menu");

        javax.swing.GroupLayout CustomerPanelLayout = new javax.swing.GroupLayout(CustomerPanel);
        CustomerPanel.setLayout(CustomerPanelLayout);
        CustomerPanelLayout.setHorizontalGroup(
            CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPanelLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(CustomerMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        CustomerPanelLayout.setVerticalGroup(
            CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(CustomerMenuLabel)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        getContentPane().add(CustomerPanel);
        CustomerPanel.setBounds(0, 0, 410, 280);

        ProductMenuLabel.setText("Product Menu");

        javax.swing.GroupLayout ProductPanelLayout = new javax.swing.GroupLayout(ProductPanel);
        ProductPanel.setLayout(ProductPanelLayout);
        ProductPanelLayout.setHorizontalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(ProductMenuLabel)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        ProductPanelLayout.setVerticalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(ProductMenuLabel)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        getContentPane().add(ProductPanel);
        ProductPanel.setBounds(0, 0, 400, 280);

        OrderMenuLabel.setText("Order Menu");

        javax.swing.GroupLayout OrderPanelLayout = new javax.swing.GroupLayout(OrderPanel);
        OrderPanel.setLayout(OrderPanelLayout);
        OrderPanelLayout.setHorizontalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(OrderMenuLabel)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        OrderPanelLayout.setVerticalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(OrderMenuLabel)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        getContentPane().add(OrderPanel);
        OrderPanel.setBounds(0, 0, 410, 280);

        jMenu1.setText("File");

        ExitDrop.setText("Exit");
        ExitDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitDropActionPerformed(evt);
            }
        });
        jMenu1.add(ExitDrop);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Navigation");

        MainNavDrop.setText("Main Menu");
        MainNavDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainNavDropActionPerformed(evt);
            }
        });
        jMenu2.add(MainNavDrop);

        CustNavDrop.setText("Customers");
        CustNavDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustNavDropActionPerformed(evt);
            }
        });
        jMenu2.add(CustNavDrop);

        ProdNavDrop.setText("Products");
        ProdNavDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdNavDropActionPerformed(evt);
            }
        });
        jMenu2.add(ProdNavDrop);

        OrdNavDrop.setText("Orders");
        OrdNavDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdNavDropActionPerformed(evt);
            }
        });
        jMenu2.add(OrdNavDrop);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainNavDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainNavDropActionPerformed
        MainPanel.setVisible(true);
        CustomerPanel.setVisible(false);
        ProductPanel.setVisible(false);
        OrderPanel.setVisible(false);
    }//GEN-LAST:event_MainNavDropActionPerformed

    private void ExitDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitDropActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitDropActionPerformed

    private void CustomerMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerMenuButtonActionPerformed
        MainPanel.setVisible(false);
        CustomerPanel.setVisible(true);
        ProductPanel.setVisible(false);
        OrderPanel.setVisible(false);
    }//GEN-LAST:event_CustomerMenuButtonActionPerformed

    private void OrderMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderMenuButtonActionPerformed
        MainPanel.setVisible(false);
        CustomerPanel.setVisible(false);
        ProductPanel.setVisible(false);
        OrderPanel.setVisible(true);
    }//GEN-LAST:event_OrderMenuButtonActionPerformed

    private void CustNavDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustNavDropActionPerformed
        MainPanel.setVisible(false);
        CustomerPanel.setVisible(true);
        ProductPanel.setVisible(false);
        OrderPanel.setVisible(false);
    }//GEN-LAST:event_CustNavDropActionPerformed

    private void OrdNavDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdNavDropActionPerformed
        MainPanel.setVisible(false);
        CustomerPanel.setVisible(false);
        ProductPanel.setVisible(false);
        OrderPanel.setVisible(true);
    }//GEN-LAST:event_OrdNavDropActionPerformed

    private void ProductMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductMenuButtonActionPerformed
        MainPanel.setVisible(false);
        CustomerPanel.setVisible(false);
        ProductPanel.setVisible(true);
        OrderPanel.setVisible(false);
    }//GEN-LAST:event_ProductMenuButtonActionPerformed

    private void ProdNavDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdNavDropActionPerformed
        MainPanel.setVisible(false);
        CustomerPanel.setVisible(false);
        ProductPanel.setVisible(true);
        OrderPanel.setVisible(false);
    }//GEN-LAST:event_ProdNavDropActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CustNavDrop;
    private javax.swing.JButton CustomerMenuButton;
    private javax.swing.JLabel CustomerMenuLabel;
    private javax.swing.JPanel CustomerPanel;
    private javax.swing.JMenuItem ExitDrop;
    private javax.swing.JLabel MainMenuLabel;
    private javax.swing.JMenuItem MainNavDrop;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JMenuItem OrdNavDrop;
    private javax.swing.JButton OrderMenuButton;
    private javax.swing.JLabel OrderMenuLabel;
    private javax.swing.JPanel OrderPanel;
    private javax.swing.JMenuItem ProdNavDrop;
    private javax.swing.JButton ProductMenuButton;
    private javax.swing.JLabel ProductMenuLabel;
    private javax.swing.JPanel ProductPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
