/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import GatewayMapper.Controller;
import GatewayMapper.ControllerInterface;
import Resources.Product;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aaron
 */
public class GUI extends javax.swing.JFrame {

    ControllerInterface con = new Controller();
    DefaultListModel model1, model2, model3;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        model1 = new DefaultListModel();
        model2 = new DefaultListModel();
        model3 = new DefaultListModel();
        MainPanel.setVisible(true);
        CustomerPanel.setVisible(false);
        ProductPanel.setVisible(false);
        OrderPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        CustomerMenuButton = new javax.swing.JButton();
        ProductMenuButton = new javax.swing.JButton();
        OrderMenuButton = new javax.swing.JButton();
        MainMenuLabel = new javax.swing.JLabel();
        CustomerPanel = new javax.swing.JPanel();
        CustomerMenuLabel = new javax.swing.JLabel();
        CutomerIDLabel = new javax.swing.JLabel();
        CustomerIDField = new javax.swing.JTextField();
        CustomerNameLabel = new javax.swing.JLabel();
        CustomerNameField = new javax.swing.JTextField();
        CustomerAddressLabel = new javax.swing.JLabel();
        CustomerAddressField = new javax.swing.JTextField();
        CustomerEmailLabel = new javax.swing.JLabel();
        CustomerEmailField = new javax.swing.JTextField();
        CustPhoneLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustPhoneTextArea = new javax.swing.JTextArea();
        AddCustomerButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CustomerJList = new javax.swing.JList();
        ExistingCustLabel = new javax.swing.JLabel();
        AddEditPhoneButton = new javax.swing.JButton();
        SaveCustomerChangeButton = new javax.swing.JButton();
        GetCustomerButton = new javax.swing.JButton();
        EditCustomerButton = new javax.swing.JButton();
        DeleteCustomerbutton = new javax.swing.JButton();
        ProductPanel = new javax.swing.JPanel();
        ProductMenuLabel = new javax.swing.JLabel();
        ProductIDField = new javax.swing.JTextField();
        ProductIDLabel = new javax.swing.JLabel();
        ProductNameLabel = new javax.swing.JLabel();
        ProductNameField = new javax.swing.JTextField();
        ProductVolumeLabel = new javax.swing.JLabel();
        ProductVolumeField = new javax.swing.JTextField();
        ProductQtyLabel = new javax.swing.JLabel();
        ProductQuantityField = new javax.swing.JTextField();
        ProductPriceLabel = new javax.swing.JLabel();
        ProductPriceField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ProductDescriptionField = new javax.swing.JTextField();
        AddProductButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ProductJList = new javax.swing.JList();
        productListLabel = new javax.swing.JLabel();
        GetProductsButton = new javax.swing.JButton();
        DeleteProductButton = new javax.swing.JButton();
        EditProductButton = new javax.swing.JButton();
        SaveProductChangesButton = new javax.swing.JButton();
        SearchForAProduct = new javax.swing.JPanel();
        ProductSearchID = new javax.swing.JLabel();
        ProductIDSearchField = new javax.swing.JTextField();
        ProductSearchName = new javax.swing.JLabel();
        ProductNameSearchField = new javax.swing.JTextField();
        SearchForProductButton = new javax.swing.JButton();
        OrderPanel = new javax.swing.JPanel();
        OrderMenuLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ExitDrop = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MainNavDrop = new javax.swing.JMenuItem();
        CustNavDrop = new javax.swing.JMenuItem();
        ProdNavDrop = new javax.swing.JMenuItem();
        OrdNavDrop = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 50, 950, 700));
        setMinimumSize(new java.awt.Dimension(950, 700));
        setPreferredSize(new java.awt.Dimension(950, 700));
        getContentPane().setLayout(null);

        CustomerMenuButton.setText("Customers");
        CustomerMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerMenuButtonActionPerformed(evt);
            }
        });

        ProductMenuButton.setText("Products");
        ProductMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductMenuButtonActionPerformed(evt);
            }
        });

        OrderMenuButton.setText("Orders");
        OrderMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderMenuButtonActionPerformed(evt);
            }
        });

        MainMenuLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        MainMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainMenuLabel.setText("Main Menu");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(MainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CustomerMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(ProductMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OrderMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(358, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(MainMenuLabel)
                .addGap(64, 64, 64)
                .addComponent(CustomerMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProductMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OrderMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        getContentPane().add(MainPanel);
        MainPanel.setBounds(0, 0, 900, 650);

        CustomerMenuLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CustomerMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CustomerMenuLabel.setText("Customer Menu");

        CutomerIDLabel.setText("Customer ID");

        CustomerIDField.setEditable(false);
        CustomerIDField.setBackground(new java.awt.Color(204, 204, 255));

        CustomerNameLabel.setText("Customer Name");

        CustomerAddressLabel.setText("Customer Address");

        CustomerEmailLabel.setText("Customer Email");

        CustPhoneLabel.setText("Customer Phone Numbers");

        CustPhoneTextArea.setColumns(20);
        CustPhoneTextArea.setRows(5);
        jScrollPane1.setViewportView(CustPhoneTextArea);

        AddCustomerButton.setText("Add Customer");
        AddCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(CustomerJList);

        ExistingCustLabel.setText("Existing Cutomers");

        AddEditPhoneButton.setText("Add / Edit Phone Number");
        AddEditPhoneButton.setEnabled(false);

        SaveCustomerChangeButton.setText("Save Changes");
        SaveCustomerChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveCustomerChangeButtonActionPerformed(evt);
            }
        });

        GetCustomerButton.setText("Get Exisitng Customer List");
        GetCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetCustomerButtonActionPerformed(evt);
            }
        });

        EditCustomerButton.setText("Edit Selected Customer");
        EditCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditCustomerButtonActionPerformed(evt);
            }
        });

        DeleteCustomerbutton.setText("Delete Selected Customer");
        DeleteCustomerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCustomerbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CustomerPanelLayout = new javax.swing.GroupLayout(CustomerPanel);
        CustomerPanel.setLayout(CustomerPanelLayout);
        CustomerPanelLayout.setHorizontalGroup(
            CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPanelLayout.createSequentialGroup()
                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerPanelLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(CustomerMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustomerPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CustPhoneLabel)
                            .addComponent(CustomerEmailLabel)
                            .addComponent(CutomerIDLabel)
                            .addComponent(CustomerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustomerNameLabel)
                            .addComponent(CustomerNameField)
                            .addComponent(CustomerAddressLabel)
                            .addComponent(CustomerAddressField)
                            .addComponent(CustomerEmailField)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(AddCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddEditPhoneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SaveCustomerChangeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(117, 117, 117)
                        .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CustomerPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(GetCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(EditCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DeleteCustomerbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(ExistingCustLabel))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        CustomerPanelLayout.setVerticalGroup(
            CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(CustomerMenuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CutomerIDLabel)
                    .addComponent(ExistingCustLabel))
                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(GetCustomerButton)
                        .addGap(18, 18, 18)
                        .addComponent(EditCustomerButton)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteCustomerbutton))
                    .addGroup(CustomerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                            .addGroup(CustomerPanelLayout.createSequentialGroup()
                                .addComponent(CustomerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CustomerNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustomerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CustomerAddressLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustomerAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CustomerEmailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustomerEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CustPhoneLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddCustomerButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddEditPhoneButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SaveCustomerChangeButton)))))
                .addContainerGap())
        );

        getContentPane().add(CustomerPanel);
        CustomerPanel.setBounds(0, 0, 900, 620);

        ProductPanel.setMinimumSize(new java.awt.Dimension(850, 700));

        ProductMenuLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ProductMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProductMenuLabel.setText("Product Menu");

        ProductIDField.setEditable(false);
        ProductIDField.setBackground(new java.awt.Color(204, 204, 255));

        ProductIDLabel.setText("Product ID");

        ProductNameLabel.setText("Product Name");

        ProductVolumeLabel.setText("Product Volume");

        ProductQtyLabel.setText("Product Quantity ");

        ProductPriceLabel.setText("Product Price");

        jLabel1.setText("Product Description");

        AddProductButton.setText("Add New Product");
        AddProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(ProductJList);

        productListLabel.setText("Existing Product list");

        GetProductsButton.setText("Get Product List");
        GetProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetProductsButtonActionPerformed(evt);
            }
        });

        DeleteProductButton.setText("Delete Product");
        DeleteProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProductButtonActionPerformed(evt);
            }
        });

        EditProductButton.setText("Edit Selected Product");
        EditProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProductButtonActionPerformed(evt);
            }
        });

        SaveProductChangesButton.setText("Save Changes");
        SaveProductChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveProductChangesButtonActionPerformed(evt);
            }
        });

        SearchForAProduct.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProductSearchID.setText("Product ID:");

        ProductSearchName.setText("Product Name:");

        SearchForProductButton.setText("Search For Item");
        SearchForProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchForProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchForAProductLayout = new javax.swing.GroupLayout(SearchForAProduct);
        SearchForAProduct.setLayout(SearchForAProductLayout);
        SearchForAProductLayout.setHorizontalGroup(
            SearchForAProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchForAProductLayout.createSequentialGroup()
                .addGroup(SearchForAProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchForAProductLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SearchForAProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProductSearchID)
                            .addComponent(ProductIDSearchField)
                            .addComponent(ProductSearchName)
                            .addComponent(ProductNameSearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                    .addGroup(SearchForAProductLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(SearchForProductButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SearchForAProductLayout.setVerticalGroup(
            SearchForAProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchForAProductLayout.createSequentialGroup()
                .addComponent(ProductSearchID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProductIDSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProductSearchName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProductNameSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchForProductButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ProductPanelLayout = new javax.swing.GroupLayout(ProductPanel);
        ProductPanel.setLayout(ProductPanelLayout);
        ProductPanelLayout.setHorizontalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProductIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductVolumeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(ProductDescriptionField)
                    .addComponent(ProductPriceField)
                    .addComponent(ProductQuantityField)
                    .addComponent(ProductVolumeField)
                    .addComponent(ProductIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductNameField)
                    .addComponent(ProductQtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveProductChangesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productListLabel)
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GetProductsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(DeleteProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchForAProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addComponent(ProductMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
        );
        ProductPanelLayout.setVerticalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(ProductMenuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductIDLabel)
                    .addComponent(productListLabel))
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ProductNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ProductVolumeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductVolumeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ProductQtyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ProductPriceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddProductButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SaveProductChangesButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(GetProductsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchForAProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditProductButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeleteProductButton)
                        .addGap(215, 215, 215))))
        );

        getContentPane().add(ProductPanel);
        ProductPanel.setBounds(0, 0, 850, 700);

        OrderMenuLabel.setText("Order Menu");

        javax.swing.GroupLayout OrderPanelLayout = new javax.swing.GroupLayout(OrderPanel);
        OrderPanel.setLayout(OrderPanelLayout);
        OrderPanelLayout.setHorizontalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(OrderMenuLabel)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        OrderPanelLayout.setVerticalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(OrderMenuLabel)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        getContentPane().add(OrderPanel);
        OrderPanel.setBounds(0, 0, 410, 280);

        jMenu1.setText("File");

        ExitDrop.setText("Exit");
        ExitDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitDropActionPerformed(evt);
            }
        });
        jMenu1.add(ExitDrop);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Navigation");

        MainNavDrop.setText("Main Menu");
        MainNavDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainNavDropActionPerformed(evt);
            }
        });
        jMenu2.add(MainNavDrop);

        CustNavDrop.setText("Customers");
        CustNavDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustNavDropActionPerformed(evt);
            }
        });
        jMenu2.add(CustNavDrop);

        ProdNavDrop.setText("Products");
        ProdNavDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdNavDropActionPerformed(evt);
            }
        });
        jMenu2.add(ProdNavDrop);

        OrdNavDrop.setText("Orders");
        OrdNavDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdNavDropActionPerformed(evt);
            }
        });
        jMenu2.add(OrdNavDrop);

        jMenuItem1.setText("jMenuItem1");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainNavDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainNavDropActionPerformed
        MainPanel.setVisible(true);
        CustomerPanel.setVisible(false);
        ProductPanel.setVisible(false);
        OrderPanel.setVisible(false);
    }//GEN-LAST:event_MainNavDropActionPerformed

    private void ExitDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitDropActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitDropActionPerformed

    private void CustomerMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerMenuButtonActionPerformed
        MainPanel.setVisible(false);
        CustomerPanel.setVisible(true);
        ProductPanel.setVisible(false);
        OrderPanel.setVisible(false);

        AddCustomerButton.setEnabled(true);
        AddEditPhoneButton.setEnabled(false);
        DeleteCustomerbutton.setEnabled(false);
        EditCustomerButton.setEnabled(false);
        GetCustomerButton.setEnabled(true);
        SaveCustomerChangeButton.setEnabled(false);
    }//GEN-LAST:event_CustomerMenuButtonActionPerformed

    private void OrderMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderMenuButtonActionPerformed
        MainPanel.setVisible(false);
        CustomerPanel.setVisible(false);
        ProductPanel.setVisible(false);
        OrderPanel.setVisible(true);
    }//GEN-LAST:event_OrderMenuButtonActionPerformed

    private void CustNavDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustNavDropActionPerformed
        MainPanel.setVisible(false);
        CustomerPanel.setVisible(true);
        ProductPanel.setVisible(false);
        OrderPanel.setVisible(false);

        AddCustomerButton.setEnabled(true);
        AddEditPhoneButton.setEnabled(false);
        DeleteCustomerbutton.setEnabled(false);
        EditCustomerButton.setEnabled(false);
        GetCustomerButton.setEnabled(true);
        SaveCustomerChangeButton.setEnabled(false);
    }//GEN-LAST:event_CustNavDropActionPerformed

    private void OrdNavDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdNavDropActionPerformed
        MainPanel.setVisible(false);
        CustomerPanel.setVisible(false);
        ProductPanel.setVisible(false);
        OrderPanel.setVisible(true);
    }//GEN-LAST:event_OrdNavDropActionPerformed

    private void ProductMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductMenuButtonActionPerformed
        MainPanel.setVisible(false);
        CustomerPanel.setVisible(false);
        ProductPanel.setVisible(true);
        OrderPanel.setVisible(false);
    }//GEN-LAST:event_ProductMenuButtonActionPerformed

    private void ProdNavDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdNavDropActionPerformed
        MainPanel.setVisible(false);
        CustomerPanel.setVisible(false);
        ProductPanel.setVisible(true);
        OrderPanel.setVisible(false);
    }//GEN-LAST:event_ProdNavDropActionPerformed

    private void GetCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetCustomerButtonActionPerformed
        model1.clear();
        CustomerJList.setModel(model1);
        con.buildCustomerList();
        for (int i = 0; i < con.getListSize(); i++) {
            model1.addElement(con.getlist(i).getCustomerID() + "-" + con.getlist(i).getName());
        }
        CustomerJList.setModel(model1);

        AddCustomerButton.setEnabled(true);
        AddEditPhoneButton.setEnabled(false);
        DeleteCustomerbutton.setEnabled(false);
        EditCustomerButton.setEnabled(true);
        GetCustomerButton.setEnabled(true);
        SaveCustomerChangeButton.setEnabled(false);
    }//GEN-LAST:event_GetCustomerButtonActionPerformed

    private void EditCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditCustomerButtonActionPerformed
        CustomerIDField.setText("" + con.getlist(CustomerJList.getSelectedIndex()).getCustomerID());
        CustomerNameField.setText(con.getlist(CustomerJList.getSelectedIndex()).getName());
        CustomerAddressField.setText(con.getlist(CustomerJList.getSelectedIndex()).getAdress());
//        PhoneID.setText(""+cg.getlist(jList1.getSelectedIndex()).getPhoneID());
        CustomerEmailField.setText(con.getlist(CustomerJList.getSelectedIndex()).getEmail());

        AddCustomerButton.setEnabled(false);
        AddEditPhoneButton.setEnabled(false);
        DeleteCustomerbutton.setEnabled(true);
        EditCustomerButton.setEnabled(true);
        GetCustomerButton.setEnabled(false);
        SaveCustomerChangeButton.setEnabled(true);
    }//GEN-LAST:event_EditCustomerButtonActionPerformed

    private void DeleteCustomerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCustomerbuttonActionPerformed
        int cusID = con.getlist(CustomerJList.getSelectedIndex()).getCustomerID();

        con.deleteCustomer(cusID);
        GetCustomerButtonActionPerformed(evt);

        CustomerIDField.setText(null);
        CustomerNameField.setText(null);
        CustomerAddressField.setText(null);
        CustPhoneTextArea.setText(null);
        CustomerEmailField.setText(null);

        AddCustomerButton.setEnabled(true);
        AddEditPhoneButton.setEnabled(false);
        DeleteCustomerbutton.setEnabled(false);
        EditCustomerButton.setEnabled(true);
        GetCustomerButton.setEnabled(true);
        SaveCustomerChangeButton.setEnabled(false);
    }//GEN-LAST:event_DeleteCustomerbuttonActionPerformed

    private void AddCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerButtonActionPerformed
        String cusName = CustomerNameField.getText();
        String cusAddress = CustomerAddressField.getText();
        String cusEmail = CustomerEmailField.getText();


        con.addCustomer(cusName, cusAddress, cusEmail);
        GetCustomerButtonActionPerformed(evt);

        CustomerIDField.setText(null);
        CustomerNameField.setText(null);
        CustomerAddressField.setText(null);
        CustPhoneTextArea.setText(null);
        CustomerEmailField.setText(null);
    }//GEN-LAST:event_AddCustomerButtonActionPerformed

    private void SaveCustomerChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveCustomerChangeButtonActionPerformed
        int cusID = Integer.parseInt(CustomerIDField.getText());
        String cusName = CustomerNameField.getText();
        String cusAddress = CustomerAddressField.getText();
        String cusEmail = CustomerEmailField.getText();

        con.saveEditedCustomer(cusID, cusName, cusAddress, cusEmail);
        GetCustomerButtonActionPerformed(evt);

        CustomerIDField.setText(null);
        CustomerNameField.setText(null);
        CustomerAddressField.setText(null);
        CustPhoneTextArea.setText(null);
        CustomerEmailField.setText(null);

        AddCustomerButton.setEnabled(true);
        AddEditPhoneButton.setEnabled(false);
        DeleteCustomerbutton.setEnabled(false);
        EditCustomerButton.setEnabled(true);
        GetCustomerButton.setEnabled(true);
        SaveCustomerChangeButton.setEnabled(false);
    }//GEN-LAST:event_SaveCustomerChangeButtonActionPerformed

    private void AddProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductButtonActionPerformed
        String empty = "";
        if (!ProductNameField.getText().equals(empty) && !ProductVolumeField.getText().equals(empty)
                && !ProductQuantityField.getText().equals(empty) && !ProductDescriptionField.getText().equals(empty)
                && !ProductPriceField.getText().equals(empty)) {

            String name = ProductNameField.getText();
            int volume = Integer.parseInt(ProductVolumeField.getText());
            int quantity = Integer.parseInt(ProductQuantityField.getText());
            String description = ProductDescriptionField.getText();
            int price = Integer.parseInt(ProductPriceField.getText());
            if (con.addProduct(name, volume, quantity, description, price)) {
                JOptionPane.showMessageDialog(this, "Product added!", "ADDED", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(this, "Could not add product!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "One or more fields are empty!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_AddProductButtonActionPerformed

    private void GetProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetProductsButtonActionPerformed
        if (con.getAllProducts()) {
            int counter = 0;
            model3.clear();
            while (counter < con.getProductListsize()) {
                model3.addElement(con.showProducts(counter));
                counter++;
            }
            ProductJList.setModel(model3);
        } else {
            JOptionPane.showMessageDialog(this, "Could not fetch products!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_GetProductsButtonActionPerformed

    private void DeleteProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteProductButtonActionPerformed
        Product deleteProd;
        deleteProd = (Product) ProductJList.getSelectedValue();

        int ID = deleteProd.getProductID();
        if (con.deleteProduct(ID)) {
            JOptionPane.showMessageDialog(this, "Product deleted!", "DELETED!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Could not delete product!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        GetProductsButtonActionPerformed(evt);
    }//GEN-LAST:event_DeleteProductButtonActionPerformed

    private void EditProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProductButtonActionPerformed
        ProductIDField.setText("" + con.showProducts(ProductJList.getSelectedIndex()).getProductID());
        ProductNameField.setText(con.showProducts(CustomerJList.getSelectedIndex()).getName());
        ProductVolumeField.setText("" + con.showProducts(CustomerJList.getSelectedIndex()).getVolume());
        ProductQuantityField.setText("" + con.showProducts(CustomerJList.getSelectedIndex()).getQuantity());
        ProductPriceField.setText("" + con.showProducts(CustomerJList.getSelectedIndex()).getPrice());
        ProductDescriptionField.setText(con.showProducts(CustomerJList.getSelectedIndex()).getDescription());

        AddProductButton.setEnabled(false);
        DeleteProductButton.setEnabled(false);
        EditProductButton.setEnabled(true);
        GetProductsButton.setEnabled(false);
        SaveProductChangesButton.setEnabled(true);
    }//GEN-LAST:event_EditProductButtonActionPerformed

    private void SaveProductChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveProductChangesButtonActionPerformed
        int ID = Integer.parseInt(ProductIDField.getText());
        String name = ProductNameField.getText();
        int volume = Integer.parseInt(ProductVolumeField.getText());
        int quantity = Integer.parseInt(ProductQuantityField.getText());
        String description = ProductDescriptionField.getText();
        int price = Integer.parseInt(ProductPriceField.getText());
        String empty = "";
        if (!ProductNameField.getText().equals(empty) && !ProductVolumeField.getText().equals(empty)
                && !ProductQuantityField.getText().equals(empty) && !ProductDescriptionField.getText().equals(empty)
                && !ProductPriceField.getText().equals(empty)) {
            if (con.editProduct(ID, name, volume, quantity, description, price)) {
                JOptionPane.showMessageDialog(this, "Product edited!", "SAVED!", JOptionPane.INFORMATION_MESSAGE);
                ProductIDField.setText(null);
                ProductNameField.setText(null);
                ProductQuantityField.setText(null);
                ProductVolumeField.setText(null);
                ProductPriceField.setText(null);
                ProductDescriptionField.setText(null);

                AddProductButton.setEnabled(true);
                DeleteProductButton.setEnabled(true);
                EditProductButton.setEnabled(true);
                GetProductsButton.setEnabled(true);
                SaveProductChangesButton.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Could not save product!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "One or more fields are empty!", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_SaveProductChangesButtonActionPerformed

    private void SearchForProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchForProductButtonActionPerformed
        String name = ProductNameSearchField.getText();
        String empty = "";
        int ID = 0;
        if (!ProductIDSearchField.getText().equals(empty)) {
            ID = Integer.parseInt(ProductIDSearchField.getText());
        }
        if (!name.isEmpty() && ID > 0) {
            if (con.searchForProduct(ID)) {
                int counter = 0;
                model3.clear();
                while (counter < con.getProductListsize()) {
                    model3.addElement(con.showProducts(counter));
                    counter++;
                }
                ProductJList.setModel(model3);

            }
        } else {
            if (!name.isEmpty()) {
                if (con.searchForProduct(name)) {
                    int counter = 0;
                    model3.clear();
                    while (counter < con.getProductListsize()) {
                        model3.addElement(con.showProducts(counter));
                        counter++;
                    }
                    ProductJList.setModel(model3);
                } else {
                    JOptionPane.showMessageDialog(this, "Could not find product!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                if (ID > 0) {
                    if (con.searchForProduct(ID)) {
                        int counter = 0;
                        model3.clear();
                        while (counter < con.getProductListsize()) {
                            model3.addElement(con.showProducts(counter));
                            counter++;
                        }
                        ProductJList.setModel(model3);
                    } else {
                        JOptionPane.showMessageDialog(this, "Could not find product!", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }


        }
        ProductIDSearchField.setText(null);
        ProductNameSearchField.setText(null);
    }//GEN-LAST:event_SearchForProductButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCustomerButton;
    private javax.swing.JButton AddEditPhoneButton;
    private javax.swing.JButton AddProductButton;
    private javax.swing.JMenuItem CustNavDrop;
    private javax.swing.JLabel CustPhoneLabel;
    private javax.swing.JTextArea CustPhoneTextArea;
    private javax.swing.JTextField CustomerAddressField;
    private javax.swing.JLabel CustomerAddressLabel;
    private javax.swing.JTextField CustomerEmailField;
    private javax.swing.JLabel CustomerEmailLabel;
    private javax.swing.JTextField CustomerIDField;
    private javax.swing.JList CustomerJList;
    private javax.swing.JButton CustomerMenuButton;
    private javax.swing.JLabel CustomerMenuLabel;
    private javax.swing.JTextField CustomerNameField;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JPanel CustomerPanel;
    private javax.swing.JLabel CutomerIDLabel;
    private javax.swing.JButton DeleteCustomerbutton;
    private javax.swing.JButton DeleteProductButton;
    private javax.swing.JButton EditCustomerButton;
    private javax.swing.JButton EditProductButton;
    private javax.swing.JLabel ExistingCustLabel;
    private javax.swing.JMenuItem ExitDrop;
    private javax.swing.JButton GetCustomerButton;
    private javax.swing.JButton GetProductsButton;
    private javax.swing.JLabel MainMenuLabel;
    private javax.swing.JMenuItem MainNavDrop;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JMenuItem OrdNavDrop;
    private javax.swing.JButton OrderMenuButton;
    private javax.swing.JLabel OrderMenuLabel;
    private javax.swing.JPanel OrderPanel;
    private javax.swing.JMenuItem ProdNavDrop;
    private javax.swing.JTextField ProductDescriptionField;
    private javax.swing.JTextField ProductIDField;
    private javax.swing.JLabel ProductIDLabel;
    private javax.swing.JTextField ProductIDSearchField;
    private javax.swing.JList ProductJList;
    private javax.swing.JButton ProductMenuButton;
    private javax.swing.JLabel ProductMenuLabel;
    private javax.swing.JTextField ProductNameField;
    private javax.swing.JLabel ProductNameLabel;
    private javax.swing.JTextField ProductNameSearchField;
    private javax.swing.JPanel ProductPanel;
    private javax.swing.JTextField ProductPriceField;
    private javax.swing.JLabel ProductPriceLabel;
    private javax.swing.JLabel ProductQtyLabel;
    private javax.swing.JTextField ProductQuantityField;
    private javax.swing.JLabel ProductSearchID;
    private javax.swing.JLabel ProductSearchName;
    private javax.swing.JTextField ProductVolumeField;
    private javax.swing.JLabel ProductVolumeLabel;
    private javax.swing.JButton SaveCustomerChangeButton;
    private javax.swing.JButton SaveProductChangesButton;
    private javax.swing.JPanel SearchForAProduct;
    private javax.swing.JButton SearchForProductButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel productListLabel;
    // End of variables declaration//GEN-END:variables
}
